AllCops:
  Exclude:
  - spec/dummy/**/*
  - coverage/**/*
  - lib/generators/sail/install/templates/**/*

Metrics/LineLength:
  Max: 140
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Max: 30
  Enabled: true
  Exclude:
    - spec/**/*
Metrics/ClassLength:
  Max: 150
Style/GuardClause:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
