require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  Exclude:
  - spec/dummy/**/*
  - coverage/**/*
  - lib/generators/sail/**/templates/**/*
  - vendor/bundle/**/*
Rails:
  Enabled: true
Rails/HttpPositionalArguments:
  Exclude:
    - spec/controllers/**/*
Metrics/LineLength:
  Max: 140
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Max: 30
  Exclude:
    - spec/**/*
Metrics/ClassLength:
  Max: 175
Style/GuardClause:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/RedundantBegin:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
