AllCops:
  Exclude:
  - spec/dummy/**/*
  - coverage/**/*
  - lib/generators/sail/**/templates/**/*

Metrics/LineLength:
  Max: 140
Metrics/MethodLength:
  Max: 20
Metrics/BlockLength:
  Max: 30
  Exclude:
    - spec/**/*
Metrics/ClassLength:
  Max: 150
Style/GuardClause:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
