number_of_parallel_jobs:
  description: Maximum number of parallel jobs
  value: 2
  cast_type: integer
  group: jobs
enable_awesome_feature:
  description: Enable the awesome feature!
  value: 'true'
  cast_type: boolean
  group: feature_flags
partner_url:
  description: URL to connect for partner service
  value: 'https://mypartner.com'
  cast_type: uri
  group: app
promotion_expire_date:
  description: Expiration date for winter promotion
  value: '2019-01-15T9:00'
  cast_type: date
  group: app
admins:
  description: List of system admins
  value: John;Ted;Mark
  cast_type: array
  group: adm
article_model:
  description: Article model to be used for posts
  value: 'Post'
  cast_type: obj_model
  group: app
new_design_percentage:
  description: Percentage of users that can see the new design
  value: '25'
  cast_type: throttle
  group: feature_flags
lucky_one_cadence:
  description: Cron definition for gitfting lucky users
  value: '6 10 2 1 *'
  cast_type: cron
  group: app
max_survey_answers:
  description: Maximum answers per user for a survey
  value: 3
  cast_type: integer
  group: app
ab_tester:
  description: General purpose ab test setting
  value: 'false'
  cast_type: ab_test
  group: feature_flags
scaler:
  description: A scaler
  value: 33
  cast_type: range
  group: tuners
